name: テスト用アクション
description: |
  テスト用アクション

inputs:
  input-a:
    description: |
      入力A
    required: true

  input-b:
    description: |
      入力B
    required: true

  cache-test-path:
    description: |
      キャッシュテストパス
    required: true

  cache-test-name:
    description: |
      キャッシュテスト名
    required: true 

outputs:
  output-a:
    description: |
      出力A
    value: ${{ steps.get-output-item.outputs.output-name }}

  cache-key:
    description: |
      キャッシュキー
    value: ${{ steps.get-cache-key.outputs.cache-key }}
    

runs:
  using: composite
  steps:
    - name: アクション内のステップ
      shell: pwsh
      id: get-output-item
      run: |
        $output_name = "${{ inputs.input-b }}".replace("${{ inputs.input-a }}", "")
        echo "output-name=$output_name" >> $env:GITHUB_OUTPUT

    - name: キャッシュキー取得
      shell: pwsh
      id: get-cache-key
      run: |
        $cache_key = "${{ inputs.cache-test-name }}-${{ hashFiles(format('{0}/**', inputs.cache-test-path)) }}"
        echo "cache-key=$cache_key" >> $env:GITHUB_OUTPUT
