name: Hello-Job

on:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

        steps:
            - name: EchoHello
              run: echo "Hello"
