name: Hello-Job1

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE
    TEST_CACHE_PATH: test/cache
    TEST_CACHE_NAME: test_cache

on:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: GetTarget
              id: get-target-name
              uses: ./.github/actions/config/test-action
              with:
                  input-a: ${{ env.SOURCE }}
                  input-b: ${{ env.ROOT }}

            - name: EchoOutput
              run: echo ${{ steps.get-target-name.outputs.output-a }}

            - name: CacheTest
              uses: actions/cache/save@v4
              with:
                  key: ${{ env.TEST_CACHE_NAME }}
                  path: ${{ env.TEST_CACHE_PATH }}
              

            
