name: Hello

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC/DDD/EEE
    ROOT: AAA/BBB/CCC
    TOXENV: A.B.C.D.E

on:
    workflow_dispatch:
    workflow_call:    
    push:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: TestReplace
              run: |
                  echo ${{ env.ROOT }}
                  echo ${{ env.SOURCE }}
                  A=${{ env.TOXENV }}
                  B=${ A//. }
                  echo ${{ A }}
              

            
