name: Hello

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC/DDD/EEE
    ROOT: AAA/BBB/CCC

on:
    workflow_dispatch:
    workflow_call:    
    push:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: TestReplace
              run: |
                  $TEST="${{ env.ROOT }}"
                  $TEST2="${TEST//AAA/}"
                  echo $TEST
                  echo $TEST2
              

            
