name: Hello-Job

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE
    CACHE_TEST_PATH: cache-test
    CACHE_TEST_NAME: cache-test

on:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref_name }}

            # Problem Machers有効化
            - name: Enable Matchers
              run: echo "::add-matcher::.github/demo_matcher.json"

            - name: GetTarget
              id: get-target-name
              uses: ./.github/actions/config/test-action
              with:
                  input-a: ${{ env.SOURCE }}
                  input-b: ${{ env.ROOT }}
                  cache-test-path: ${{ env.CACHE_TEST_PATH }}
                  cache-test-name: ${{ env.CACHE_TEST_NAME }}

            - name: EchoAnnotations0
              run: .\test.ps1
