name: Hello

env:
    TEXT_PATH: my_text.txt

on:
    workflow_dispatch:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Hello
              run: python hello.py
            
            - name: Run Output Text
              run: python output_text.py ${{env.TEXT_PATH}}