name: Hello

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE

on:
    workflow_dispatch:
    workflow_call:    
    push:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: GetTarget
              id: get-target-name
              run: |
                  $target = "${{ env.ROOT }}".replace("${{ env.SOURCE }}", "")
                  echo "::set-output name=target::$target"

            - name: TestReplace
              run: echo ${{ steps.get-target-name.outputs.target }}
                  
              

            
