name: Hello-Job

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE
    CACHE_TEST_PATH: cache-test
    CACHE_TEST_NAME: cache-test

on:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref_name }}

            # - name: PythonSetup
            #   uses: ./.github/actions/setup-python

            - name: GetTarget
              id: get-target-name
              uses: ./.github/actions/config/test-action
              with:
                  input-a: ${{ env.SOURCE }}
                  input-b: ${{ env.ROOT }}
                  cache-test-path: ${{ env.CACHE_TEST_PATH }}
                  cache-test-name: ${{ env.CACHE_TEST_NAME }}

            - name: EchoAnnotations0
              run: |
                  echo "::error title=ErrorTest0::This is Error Test0"
                  echo "::error title=ErrorTest1::This is Error Test1"
                  echo "::error title=ErrorTest2::This is Error Test2"
                  echo "::error title=ErrorTest3::This is Error Test3"
                  echo "::error title=ErrorTest4::This is Error Test4"
                  echo "::error title=ErrorTest5::This is Error Test5"
                  echo "::error title=ErrorTest6::This is Error Test6"
                  echo "::error title=ErrorTest7::This is Error Test7"
                  echo "::error title=ErrorTest8::This is Error Test8"
                  echo "::error title=ErrorTest9::This is Error Test9"
                  echo "::warning title=WarningTest0::This is Warning Test0"
                  echo "::warning title=WarningTest1::This is Warning Test1"
                  echo "::warning title=WarningTest2::This is Warning Test2"
                  echo "::warning title=WarningTest3::This is Warning Test3"
                  echo "::warning title=WarningTest4::This is Warning Test4"
                  echo "::warning title=WarningTest5::This is Warning Test5"
                  echo "::warning title=WarningTest6::This is Warning Test6"
                  echo "::warning title=WarningTest7::This is Warning Test7"
                  echo "::warning title=WarningTest8::This is Warning Test8"
                  echo "::warning title=WarningTest9::This is Warning Test9"
                  echo "::notice title=NoticeTest0::This is Notice Test0"
                  echo "::notice title=NoticeTest1::This is Notice Test1"
                  echo "::notice title=NoticeTest2::This is Notice Test2"
                  echo "::notice title=NoticeTest3::This is Notice Test3"
                  echo "::notice title=NoticeTest4::This is Notice Test4"
                  echo "::notice title=NoticeTest5::This is Notice Test5"
                  echo "::notice title=NoticeTest6::This is Notice Test6"
                  echo "::notice title=NoticeTest7::This is Notice Test7"
                  echo "::notice title=NoticeTest8::This is Notice Test8"
                  echo "::notice title=NoticeTest9::This is Notice Test9"

            - name: EchoAnnotations1
              run: |
                  echo "::error title=ErrorTest10::This is Error Test10"
                  echo "::error title=ErrorTest11::This is Error Test11"
                  echo "::error title=ErrorTest12::This is Error Test12"
                  echo "::error title=ErrorTest13::This is Error Test13"
                  echo "::error title=ErrorTest14::This is Error Test14"
                  echo "::error title=ErrorTest15::This is Error Test15"
                  echo "::error title=ErrorTest16::This is Error Test16"
                  echo "::error title=ErrorTest17::This is Error Test17"
                  echo "::error title=ErrorTest18::This is Error Test18"
                  echo "::error title=ErrorTest19::This is Error Test19"
                  echo "::warning title=WarningTest10::This is Warning Test10"
                  echo "::warning title=WarningTest11::This is Warning Test11"
                  echo "::warning title=WarningTest12::This is Warning Test12"
                  echo "::warning title=WarningTest13::This is Warning Test13"
                  echo "::warning title=WarningTest14::This is Warning Test14"
                  echo "::warning title=WarningTest15::This is Warning Test15"
                  echo "::warning title=WarningTest16::This is Warning Test16"
                  echo "::warning title=WarningTest17::This is Warning Test17"
                  echo "::warning title=WarningTest18::This is Warning Test18"
                  echo "::warning title=WarningTest19::This is Warning Test19"
                  echo "::notice title=NoticeTest10::This is Notice Test10"
                  echo "::notice title=NoticeTest11::This is Notice Test11"
                  echo "::notice title=NoticeTest12::This is Notice Test12"
                  echo "::notice title=NoticeTest13::This is Notice Test13"
                  echo "::notice title=NoticeTest14::This is Notice Test14"
                  echo "::notice title=NoticeTest15::This is Notice Test15"
                  echo "::notice title=NoticeTest16::This is Notice Test16"
                  echo "::notice title=NoticeTest17::This is Notice Test17"
                  echo "::notice title=NoticeTest18::This is Notice Test18"
                  echo "::notice title=NoticeTest19::This is Notice Test19"

            - name: EchoAnnotations2
              run: |
                  echo "::error title=ErrorTest20::This is Error Test20"
                  echo "::error title=ErrorTest21::This is Error Test21"
                  echo "::error title=ErrorTest22::This is Error Test22"
                  echo "::error title=ErrorTest23::This is Error Test23"
                  echo "::error title=ErrorTest24::This is Error Test24"
                  echo "::error title=ErrorTest25::This is Error Test25"
                  echo "::error title=ErrorTest26::This is Error Test26"
                  echo "::error title=ErrorTest27::This is Error Test27"
                  echo "::error title=ErrorTest28::This is Error Test28"
                  echo "::error title=ErrorTest29::This is Error Test29"
                  echo "::warning title=WarningTest20::This is Warning Test20"
                  echo "::warning title=WarningTest21::This is Warning Test21"
                  echo "::warning title=WarningTest22::This is Warning Test22"
                  echo "::warning title=WarningTest23::This is Warning Test23"
                  echo "::warning title=WarningTest24::This is Warning Test24"
                  echo "::warning title=WarningTest25::This is Warning Test25"
                  echo "::warning title=WarningTest26::This is Warning Test26"
                  echo "::warning title=WarningTest27::This is Warning Test27"
                  echo "::warning title=WarningTest28::This is Warning Test28"
                  echo "::warning title=WarningTest29::This is Warning Test29"
                  echo "::notice title=NoticeTest20::This is Notice Test20"
                  echo "::notice title=NoticeTest21::This is Notice Test21"
                  echo "::notice title=NoticeTest22::This is Notice Test22"
                  echo "::notice title=NoticeTest23::This is Notice Test23"
                  echo "::notice title=NoticeTest24::This is Notice Test24"
                  echo "::notice title=NoticeTest25::This is Notice Test25"
                  echo "::notice title=NoticeTest26::This is Notice Test26"
                  echo "::notice title=NoticeTest27::This is Notice Test27"
                  echo "::notice title=NoticeTest28::This is Notice Test28"
                  echo "::notice title=NoticeTest29::This is Notice Test29"

            - name: EchoAnnotations3
              run: |
                  echo "::error title=ErrorTest30::This is Error Test30"
                  echo "::error title=ErrorTest31::This is Error Test31"
                  echo "::error title=ErrorTest32::This is Error Test32"
                  echo "::error title=ErrorTest33::This is Error Test33"
                  echo "::error title=ErrorTest34::This is Error Test34"
                  echo "::error title=ErrorTest35::This is Error Test35"
                  echo "::error title=ErrorTest36::This is Error Test36"
                  echo "::error title=ErrorTest37::This is Error Test37"
                  echo "::error title=ErrorTest38::This is Error Test38"
                  echo "::error title=ErrorTest39::This is Error Test39"
                  echo "::warning title=WarningTest30::This is Warning Test30"
                  echo "::warning title=WarningTest31::This is Warning Test31"
                  echo "::warning title=WarningTest32::This is Warning Test32"
                  echo "::warning title=WarningTest33::This is Warning Test33"
                  echo "::warning title=WarningTest34::This is Warning Test34"
                  echo "::warning title=WarningTest35::This is Warning Test35"
                  echo "::warning title=WarningTest36::This is Warning Test36"
                  echo "::warning title=WarningTest37::This is Warning Test37"
                  echo "::warning title=WarningTest38::This is Warning Test38"
                  echo "::warning title=WarningTest39::This is Warning Test39"
                  echo "::notice title=NoticeTest30::This is Notice Test30"
                  echo "::notice title=NoticeTest31::This is Notice Test31"
                  echo "::notice title=NoticeTest32::This is Notice Test32"
                  echo "::notice title=NoticeTest33::This is Notice Test33"
                  echo "::notice title=NoticeTest34::This is Notice Test34"
                  echo "::notice title=NoticeTest35::This is Notice Test35"
                  echo "::notice title=NoticeTest36::This is Notice Test36"
                  echo "::notice title=NoticeTest37::This is Notice Test37"
                  echo "::notice title=NoticeTest38::This is Notice Test38"
                  echo "::notice title=NoticeTest39::This is Notice Test39"

            - name: EchoAnnotations4
              run: |
                  echo "::error title=ErrorTest40::This is Error Test40"
                  echo "::error title=ErrorTest41::This is Error Test41"
                  echo "::error title=ErrorTest42::This is Error Test42"
                  echo "::error title=ErrorTest43::This is Error Test43"
                  echo "::error title=ErrorTest44::This is Error Test44"
                  echo "::error title=ErrorTest45::This is Error Test45"
                  echo "::error title=ErrorTest46::This is Error Test46"
                  echo "::error title=ErrorTest47::This is Error Test47"
                  echo "::error title=ErrorTest48::This is Error Test48"
                  echo "::error title=ErrorTest49::This is Error Test49"
                  echo "::warning title=WarningTest40::This is Warning Test40"
                  echo "::warning title=WarningTest41::This is Warning Test41"
                  echo "::warning title=WarningTest42::This is Warning Test42"
                  echo "::warning title=WarningTest43::This is Warning Test43"
                  echo "::warning title=WarningTest44::This is Warning Test44"
                  echo "::warning title=WarningTest45::This is Warning Test45"
                  echo "::warning title=WarningTest46::This is Warning Test46"
                  echo "::warning title=WarningTest47::This is Warning Test47"
                  echo "::warning title=WarningTest48::This is Warning Test48"
                  echo "::warning title=WarningTest49::This is Warning Test49"
                  echo "::notice title=NoticeTest40::This is Notice Test40"
                  echo "::notice title=NoticeTest41::This is Notice Test41"
                  echo "::notice title=NoticeTest42::This is Notice Test42"
                  echo "::notice title=NoticeTest43::This is Notice Test43"
                  echo "::notice title=NoticeTest44::This is Notice Test44"
                  echo "::notice title=NoticeTest45::This is Notice Test45"
                  echo "::notice title=NoticeTest46::This is Notice Test46"
                  echo "::notice title=NoticeTest47::This is Notice Test47"
                  echo "::notice title=NoticeTest48::This is Notice Test48"
                  echo "::notice title=NoticeTest49::This is Notice Test49"
