name: Hello-Job

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE
    CACHE_TEST_PATH: cache-test
    CACHE_TEST_NAME: cache-test

on:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref_name }}

            # Problem Machers有効化
            - name: Enable Matchers
              run: echo "::add-matcher::.github/demo_matcher.json"

            - name: GetTarget
              id: get-target-name
              uses: ./.github/actions/config/test-action
              with:
                  input-a: ${{ env.SOURCE }}
                  input-b: ${{ env.ROOT }}
                  cache-test-path: ${{ env.CACHE_TEST_PATH }}
                  cache-test-name: ${{ env.CACHE_TEST_NAME }}

            - name: EchoAnnotations0
              run: |
                  echo "::error title=ErrorTest0::This is Error Test0"
                  echo "::error title=ErrorTest1::This is Error Test1"
                  echo "::error title=ErrorTest2::This is Error Test2"
                  echo "::error title=ErrorTest3::This is Error Test3"
                  echo "::warning title=WarningTest0::This is Warning Test0"
                  echo "::warning title=WarningTest1::This is Warning Test1"
                  echo "::warning title=WarningTest2::This is Warning Test2"
                  echo "::notice title=NoticeTest0::This is Notice Test0"
                  echo "::notice title=NoticeTest1::This is Notice Test1"
                  echo "::notice title=NoticeTest2::This is Notice Test2"
                  echo "::notice title=NoticeTest3::This is Notice Test3"

            - name: EchoAnnotations1
              run: |
                  echo "::error title=ErrorTest10::This is Error Test10"
                  echo "::error title=ErrorTest11::This is Error Test11"
                  echo "::error title=ErrorTest12::This is Error Test12"
                  echo "::warning title=WarningTest10::This is Warning Test10"
                  echo "::warning title=WarningTest11::This is Warning Test11"
                  echo "::warning title=WarningTest12::This is Warning Test12"
                  echo "::warning title=WarningTest13::This is Warning Test13"
                  echo "::notice title=NoticeTest10::This is Notice Test10"
                  echo "::notice title=NoticeTest11::This is Notice Test11"
                  echo "::notice title=NoticeTest12::This is Notice Test12"

            - name: EchoAnnotations2
              run: |
                  echo "::error title=ErrorTest20::This is Error Test20"
                  echo "::error title=ErrorTest21::This is Error Test21"
                  echo "::error title=ErrorTest22::This is Error Test22"
                  echo "::warning title=WarningTest20::This is Warning Test20"
                  echo "::warning title=WarningTest21::This is Warning Test21"
                  echo "::warning title=WarningTest22::This is Warning Test22"
                  echo "::notice title=NoticeTest20::This is Notice Test20"
                  echo "::notice title=NoticeTest21::This is Notice Test21"
                  echo "::notice title=NoticeTest22::This is Notice Test22"
                  echo "::notice title=NoticeTest23::This is Notice Test23"

            - name: EchoAnnotations3
              run: |
                  echo "::error title=ErrorTest30::This is Error Test30"
                  echo "::error title=ErrorTest31::This is Error Test31"
                  echo "::error title=ErrorTest32::This is Error Test32"
                  echo "::error title=ErrorTest33::This is Error Test33"
                  echo "::warning title=WarningTest30::This is Warning Test30"
                  echo "::warning title=WarningTest31::This is Warning Test31"
                  echo "::warning title=WarningTest32::This is Warning Test32"
                  echo "::notice title=NoticeTest30::This is Notice Test30"
                  echo "::notice title=NoticeTest31::This is Notice Test31"
                  echo "::notice title=NoticeTest32::This is Notice Test32"

            - name: EchoAnnotations4
              run: |
                  echo "Error:error"
                  echo "Warning:warning"
                  echo "Info:info"

            # Problem Machers無効化
            - name: Disable Matchers
              run: echo "::remove-matcher owner=hello_demo::"
