name: Hello-Job

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE
    CACHE_TEST_PATH: cache-test
    CACHE_TEST_NAME: cache-test

on:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref_name }}

            # - name: PythonSetup
            #   uses: ./.github/actions/setup-python

            - name: GetTarget
              id: get-target-name
              uses: ./.github/actions/config/test-action
              with:
                  input-a: ${{ env.SOURCE }}
                  input-b: ${{ env.ROOT }}
                  cache-test-path: ${{ env.CACHE_TEST_PATH }}
                  cache-test-name: ${{ env.CACHE_TEST_NAME }}

            - name: EchoOutput
              id: echo-output
              run: |
                  echo "::error title=ErrorTest::This is Error Test"
                  echo "::error title=ErrorTest2::This is Error Test2"
                  echo "::warning title=WarningTest::This is Warning Test"
                  echo "::warning title=WarningTest2::This is Warning Test2"
                  echo "::notice title=NoticeTest::This is Notice Test"
                  echo "::notice title=NoticeTest2::This is Notice Test2"
