name: Hello

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC/DDD/EEE
    ROOT: AAA/BBB/CCC
    TOXENV: "py${{ matrix.python }}-django${{ matrix.django }}"

on:
    workflow_dispatch:
    workflow_call:    
    push:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: TestReplace
              run: |
                  echo ${{ env.ROOT }}
                  echo ${{ env.SOURCE }}
                  TOXENV=${{ env.TOXENV }}
                  TOXENV=${ TOXENV//. }
                  echo ${{ TOXENV }}
              

            
