name: Hello

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE

on:
    workflow_dispatch:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: GetTarget
              id: get-target-name
              uses: ./.github/actions/test-action
              with:
                  input-a: ${{ env.SOURCE }}
                  input-b: ${{ env.ROOT }}

            - name: EchoOutput
              run: echo ${{ steps.get-target-name.outputs.output-a }}

            - name: EchoHello
              uses: ./.github/workflows/jobs/hello-job.yml
                  
              

            
