name: Hello

env:
    TEXT_DIR: my_text

on:
    workflow_dispatch:
    workflow_call:
    push:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: Run Hello
              run: |
                  python hello.py
                  echo $GITHUB_ENV
                  echo $LastExitCode
                  echo "RESULT=$LastExitCode" >> $env:GITHUB_ENV
                  echo ${{ github.actor }}
                  echo ${{ steps.checkout.outputs.ref }}
                  echo ${{ steps.checkout.outputs.commit }}
              continue-on-error: true
            
            - name: Run Output Text
              run: python output_text.py ${{env.TEXT_DIR}}
            
            - name: Restore Cache
              uses: actions/cache/restore@v4
              with:
                key: my-cache-${{github.ref_name}}
                path: ${{env.TEXT_DIR}}
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: ${{env.TEXT_DIR}}

            - name: Check Exit Code
              run: exit $env:RESULT
