name: Hello-Job

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE
    CACHE_TEST_PATH: cache-test
    CACHE_TEST_NAME: cache-test

on:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref_name }}

            # - name: PythonSetup
            #   uses: ./.github/actions/setup-python

            - name: GetTarget
              id: get-target-name
              uses: ./.github/actions/config/test-action
              with:
                  input-a: ${{ env.SOURCE }}
                  input-b: ${{ env.ROOT }}
                  cache-test-path: ${{ env.CACHE_TEST_PATH }}
                  cache-test-name: ${{ env.CACHE_TEST_NAME }}

            - name: EchoAnnotations1
              id: echo-ann1
              run: |
                  echo "::error title=ErrorTest0::This is Error Test0"
                  echo "::error title=ErrorTest1::This is Error Test1"
                  echo "::error title=ErrorTest2::This is Error Test2"
                  echo "::error title=ErrorTest3::This is Error Test3"
                  echo "::error title=ErrorTest4::This is Error Test4"
                  echo "::error title=ErrorTest5::This is Error Test5"
                  echo "::error title=ErrorTest6::This is Error Test6"
                  echo "::error title=ErrorTest7::This is Error Test7"
                  echo "::error title=ErrorTest8::This is Error Test8"
                  echo "::error title=ErrorTest9::This is Error Test9"
                  echo "::warning title=WarningTest0::This is Warning Test0"
                  echo "::warning title=WarningTest1::This is Warning Test1"
                  echo "::warning title=WarningTest2::This is Warning Test2"
                  echo "::warning title=WarningTest3::This is Warning Test3"
                  echo "::warning title=WarningTest4::This is Warning Test4"
                  echo "::warning title=WarningTest5::This is Warning Test5"
                  echo "::warning title=WarningTest6::This is Warning Test6"
                  echo "::warning title=WarningTest7::This is Warning Test7"
                  echo "::warning title=WarningTest8::This is Warning Test8"
                  echo "::warning title=WarningTest9::This is Warning Test9"
                  echo "::notice title=NoticeTest0::This is Notice Test0"
                  echo "::notice title=NoticeTest1::This is Notice Test1"
                  echo "::notice title=NoticeTest2::This is Notice Test2"
                  echo "::notice title=NoticeTest3::This is Notice Test3"
                  echo "::notice title=NoticeTest4::This is Notice Test4"
                  echo "::notice title=NoticeTest5::This is Notice Test5"
                  echo "::notice title=NoticeTest6::This is Notice Test6"
                  echo "::notice title=NoticeTest7::This is Notice Test7"
                  echo "::notice title=NoticeTest8::This is Notice Test8"
                  echo "::notice title=NoticeTest9::This is Notice Test9"

            - name: EchoAnnotations2
              id: echo-ann2
              run: |
                  echo "::error title=ErrorTest10::This is Error Test10"
                  echo "::error title=ErrorTest11::This is Error Test11"
                  echo "::error title=ErrorTest12::This is Error Test12"
                  echo "::warning title=WarningTest10::This is Warning Test10"
                  echo "::warning title=WarningTest11::This is Warning Test11"
                  echo "::warning title=WarningTest12::This is Warning Test12"
                  echo "::notice title=NoticeTest10::This is Notice Test10"
                  echo "::notice title=NoticeTest11::This is Notice Test11"
                  echo "::notice title=NoticeTest12::This is Notice Test12"
