name: Hello-Job

env:
    TEXT_DIR: my_text
    SOURCE: AAA/BBB/CCC
    ROOT: AAA/BBB/CCC/DDD/EEE
    CACHE_TEST_PATH: cache-test
    CACHE_TEST_NAME: cache-test

on:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.ref_name }}

            # - name: PythonSetup
            #   uses: ./.github/actions/setup-python

            - name: GetTarget
              id: get-target-name
              uses: ./.github/actions/config/test-action
              with:
                  input-a: ${{ env.SOURCE }}
                  input-b: ${{ env.ROOT }}
                  cache-test-path: ${{ env.CACHE_TEST_PATH }}
                  cache-test-name: ${{ env.CACHE_TEST_NAME }}

            - name: EchoOutput
              id: echo-output
              run: |
                  echo ${{ steps.get-target-name.outputs.cache-key }}

            - name: CheckEchoOutputA
              if: ${{ steps.get-target-name.outputs.output-a == '' }}
              run: echo "OK"

            - name: CHCPCHECK
              run: echo "${{ github.ref_name }}"

            - name: Get Runner Infos
              uses: embedded-community/get-runner-labels-action@v1
              id: runner-labels

            - name: Print Runner Labels
              run: echo ${{ steps.runner-labels.outputs.labels }}
