name: Hello

env:
    TEXT_DIR: my_text

on:
    workflow_dispatch:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Hello
              run: python hello.py
            
            - name: Run Output Text
              run: python output_text.py ${{env.TEXT_DIR}}
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: ${{env.TEXT_DIR}}