name: Hello

env:
    TEXT_DIR: my_text

on:
    workflow_dispatch:
    workflow_call:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Hello
              run: |
                  python hello.py
                  echo $LastExitCode
                  echo "RESULT=$LastExitCode" >> "$GITHUB_ENV"
              continue-on-error: true
            
            - name: Run Output Text
              run: python output_text.py ${{env.TEXT_DIR}}
            
            - name: Restore Cache
              uses: actions/cache/restore@v4
              with:
                key: my-cache-${{github.ref_name}}
                path: ${{env.TEXT_DIR}}
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: ${{env.TEXT_DIR}}

            - name: Check Exit Code
              run: exit $RESULT
