name: Hello

on:
    workflow_dispatch:

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Hello
              run: python hello.py