name: Hello

env:
    TEXT_DIR: my_text

on:
    workflow_dispatch:
        inputs:
            source:
                description: |
                  ソース
                required: false
                default: AAA/BBB/CCC/DDD/EEE

            root:
                description: |
                  ルート
                required: false
                default: AAA/BBB/CCC
    workflow_call:    

jobs:
    hello:
        runs-on: windows-latest

        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4

            - name: TestReplace
              run: echo ${{ inputs.source }}.Replace(${{ inputs.root }}, "")
              

            
